### ISSUE TITLE
BUG: EndOfWeek may go to the next week when it is sunday! 

### ISSUE THREAD

**Issue by iflamed** [uniplaces/carbon#61]
```go
package main

import (
	"fmt"

	"github.com/uniplaces/carbon"
)

func main() {
	t, err := carbon.Parse("2006-01-02", "2021-01-17", "Asia/Shanghai")
	t = t.EndOfWeek()
	fmt.Println(t)
	fmt.Println(err)
}
```
[try this link https://play.golang.org/p/BB5A7HM1TYZ](https://play.golang.org/p/BB5A7HM1TYZ)

**Comment by tlfbrito** [comment]
This should be fixed now

**Comment by helbing** [comment]
@tlfbrito Hi, still have this problem. uniplaces/carbon v0.1.6.
